-- 创建应用数据库用户p1
CREATE USER p1 WITH PASSWORD '${APP_POSTGRES_PASSWORD}';

-- 创建应用数据库p1
CREATE DATABASE p1 OWNER p1;

-- 为p1用户授予必要的权限
GRANT ALL PRIVILEGES ON DATABASE p1 TO p1;

-- 在p1数据库中为p1用户授予所有权限
\c p1;
GRANT ALL ON SCHEMA public TO p1;
GRANT ALL ON ALL TABLES IN SCHEMA public TO p1;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO p1;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO p1;

-- 设置默认权限，确保新创建的对象也有正确权限
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO p1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO p1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO p1;

-- 可选：如果需要跨数据库访问（高级用法），可以授予有限权限
-- GRANT USAGE ON SCHEMA graph_node TO p1;
-- GRANT SELECT ON ALL TABLES IN SCHEMA graph_node TO p1;
